### ISSUE TITLE
Github CI: CUDA build times can be significantly reduced ( roughly by 80-90% )

### ISSUE THREAD

**Issue by staviq** [ggerganov/llama.cpp#3232]
Currently, CUDA CI build jobs take 20min and sometimes more, simply because full CUDA package is being downloaded:

![image](https://github.com/ggerganov/llama.cpp/assets/15910535/f7150296-6217-4d6f-86bd-e2db51a7629c)

This is how long it takes, with the change, in a VM, on my laptop, over 20Mbit internet connection (~4min):

![image](https://github.com/ggerganov/llama.cpp/assets/15910535/f9950afc-b3f6-4ebb-8920-4118f05ff51a)

Docs for CUDA toolkit github action mention `method` parameter, which isn't being used, yet the fact `sub-packages` are specified, suggests it was the original intention to install only necessary part of the CUDA toolkit.

This simple change in `build.yml` allows reducing time spent preparing CUDA toolkit drastically, even though necessary installation files ( ~230M ) weren't cached in my test:

```yaml
      - uses: Jimver/cuda-toolkit@v0.2.11
        id: cuda-toolkit
        with:
          cuda: ${{ matrix.cuda }}
          method: network
          sub-packages: '["nvcc", "cudart", "cublas", "cublas_dev", "thrust", "visual_studio_integration"]'
```

Edit: For reference: https://github.com/marketplace/actions/cuda-toolkit#method
