### ISSUE TITLE
Support speculative decoding in `server` example

### ISSUE THREAD

**Issue by mscheong01** [ggerganov/llama.cpp#5877]
# Prerequisites

Please answer the following questions for yourself before submitting an issue.

- [x] I am running the latest code. Development is very rapid so there are no tagged versions as of now.
- [x] I carefully followed the [README.md](https://github.com/ggerganov/llama.cpp/blob/master/README.md).
- [x] I [searched using keywords relevant to my issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/filtering-and-searching-issues-and-pull-requests) to make sure that I am creating a new issue that is not already open (or closed).
- [x] I reviewed the [Discussions](https://github.com/ggerganov/llama.cpp/discussions), and have a new bug or useful enhancement to share.

# Feature Description

provide speculative decoding through `server` example.

# Motivation

Noticed this topic popped up in several comments ([1](https://github.com/ggerganov/llama.cpp/issues/4286#issuecomment-1839494720), [2](https://github.com/ggerganov/llama.cpp/issues/4216#issuecomment-1826380687), [3](https://github.com/ggerganov/llama.cpp/issues/4216#issuecomment-1970810228)) but it seems we haven't officially opened an issue for it. I'm creating this to provide a space for focused discussion on how we can implement this feature and actually get this started.

# Possible Implementation

perhaps move speculative sampling implementation to `common` or `sampling`?

**Comment by vietanh125** [comment]
Any updates for this?

**Comment by mscheong01** [comment]
@vietanh125 Not yet, but contributions are welcome 😃

**Comment by ggerganov** [comment]
There is ongoing related work in https://github.com/ggerganov/llama.cpp/pull/6828. Though I haven't had time to look in details yet

**Comment by kerthcet** [comment]
Sorry, does that means the server doesn't support speculative decoding? However, I can run it with commands like below in Kubernetes

Just a sample:
```
spec:
  containers:
  - args:
    - -m
    - /workspace/models/llama-2-7b.Q8_0.gguf
    - -md
    - /workspace/models/llama-2-7b.Q2_K.gguf
    - --port
    - "8080"
    - --host
    - 0.0.0.0
    - -fa
    command:
    - ./llama-server
```
