### ISSUE TITLE
Quantization fails for low bit quants (Including Q2_K_S) of pass-through merged (Frankensteined) models with error: Missing importance matrix for tensor blk.40.ffn_down.weight in a very low-bit quantization. The result will be garbage, so bailing out

### ISSUE THREAD

**Issue by joseph777111** [ggerganov/llama.cpp#6249]
Quantization Fails for low bit quants of [**pass-through**](https://github.com/arcee-ai/mergekit#passthrough) merged models with error: Missing importance matrix for tensor blk.40.ffn_down.weight in a very low-bit quantization The result will be garbage, so bailing out.

Note:  [Joseph717171/BigOrca-2-XB](https://huggingface.co/Joseph717171/BigOrca-2-XB) does quantize - and functions normally - for normal quants, including: IQuants larger than IQ2_M (So: Q2_K - Q8_0).

System:
OS: Mac OS Sonoma v14.3.1
2020 M1 MacBook Pro 16GB UnifiedMemory
GPU: 8 Cores
CPU: 8 Cores (4 Performance and 4 Efficiency...)

Merged Model: [Joseph717171/BigOrca-2-XB](https://huggingface.co/Joseph717171/BigOrca-2-XB)

Imatrix: [BigOrca-2-XB_wikitext_raw.imatrix](https://huggingface.co/Joseph717171/Imatrices/blob/main/BigOrca-2-XB_wikitext_raw.imatrix) (From: [Joseph717171/Imatrices](https://huggingface.co/Joseph717171/Imatrices/tree/main))

Error:
```
[ 246/ 633]               blk.40.ffn_down.weight - [13824,  5120,     1,     1], type =    f16, 
====== llama_model_quantize_internal: did not find weights for blk.40.ffn_down.weight


============================================================
Missing importance matrix for tensor blk.40.ffn_down.weight in a very low-bit quantization
The result will be garbage, so bailing out
============================================================

llama_model_quantize: failed to quantize: Missing importance matrix for tensor blk.40.ffn_down.weight in a very low-bit quantization
main: failed to quantize model from '/Users/jsarnecki/opt/Joseph717171/BigOrca-2-XB/ggml-model-f16.gguf'

```
[failed_quant_BigOrca-2-XB_IQ2_K_S.log](https://github.com/ggerganov/llama.cpp/files/14729981/failed_quant_BigOrca-2-XB_IQ2_K_S.log)
[failed_quant_BigOrca-2-XB_IQ2_M.log](https://github.com/ggerganov/llama.cpp/files/14729982/failed_quant_BigOrca-2-XB_IQ2_M.log)

Here's the merge recipe:

```yaml
dtype: float16
merge_method: passthrough
slices:
- sources:
  - layer_range: [0, 10]
    model: /Users/jsarnecki/opt/microsoft-Orca-2-13b
- sources:
  - layer_range: [5, 15]
    model: /Users/jsarnecki/opt/microsoft-Orca-2-13b
- sources:
  - layer_range: [10, 20]
    model: /Users/jsarnecki/opt/microsoft-Orca-2-13b
- sources:
  - layer_range: [15, 25]
    model: /Users/jsarnecki/opt/microsoft-Orca-2-13b
- sources:
  - layer_range: [20, 30]
    model: /Users/jsarnecki/opt/microsoft-Orca-2-13b
- sources:
  - layer_range: [25, 35]
    model: /Users/jsarnecki/opt/microsoft-Orca-2-13b
- sources:
  - layer_range: [30, 40]
    model: /Users/jsarnecki/opt/microsoft-Orca-2-13b
```

As you can see, the 40<sup>th</sup> layer is present, so I am confused how this error and issue can occur. 🤔🫤

@ikawrakow, et al. any help or insight would be much appreciated. Thanks 🙏
